module.exports = {
  name: "Program Theme",

  page: {
    marginTopMm: 16,
    marginBottomMm: 16,
    marginLeftMm: 18,
    marginRightMm: 18,
    format: "a4",
    orientation: "portrait",
    unit: "mm",
    compress: true,
    backgroundColor: [255, 252, 248],
    defaultText: {
      fontFamily: "helvetica",
      fontStyle: "normal",
      fontSize: 10,
      color: [0, 0, 0],
      lineHeight: 1.2,
    },
    defaultStroke: {
      color: [0, 0, 0],
      lineWidth: 0.2,
      lineCap: "butt",
      lineJoin: "miter",
    },
    defaultFillColor: [255, 252, 248],
  },

  labels: {
    "program.footer.rule": {
      color: [251, 146, 60],
      lineWidth: 0.25,
      marginBottomPx: 2,
    },
    "program.footer.left": {
      fontFamily: "helvetica",
      fontStyle: "normal",
      fontSize: 7.5,
      color: [120, 113, 108],
      marginBottomPx: 0,
    },
    "program.footer.right": {
      fontFamily: "helvetica",
      fontStyle: "bold",
      fontSize: 7.5,
      color: [120, 113, 108],
      marginBottomPx: 0,
    },
    "program.kicker": {
      fontFamily: "helvetica",
      fontStyle: "bold",
      fontSize: 8,
      textTransform: "upper",
      color: [13, 148, 136],
      align: "center",
      marginBottomPx: 4,
    },
    "program.title": {
      fontFamily: "helvetica",
      fontStyle: "bold",
      fontSize: 23,
      align: "center",
      color: [41, 37, 36],
      marginBottomPx: 4,
    },
    "program.subtitle": {
      fontFamily: "helvetica",
      fontStyle: "normal",
      fontSize: 10,
      align: "center",
      color: [120, 113, 108],
      marginBottomPx: 8,
    },
    "program.divider": {
      color: [251, 146, 60],
      lineWidth: 0.35,
      marginBottomPx: 8,
    },
    "program.day": {
      fontFamily: "helvetica",
      fontStyle: "bold",
      fontSize: 10,
      textTransform: "upper",
      color: [234, 88, 12],
      marginTopPx: 8,
      marginBottomPx: 4,
      leftBorder: {
        color: [13, 148, 136],
        widthMm: 1.4,
        gapMm: 2.5,
      },
    },
    "program.slot.time": {
      fontFamily: "helvetica",
      fontStyle: "bold",
      fontSize: 8.6,
      color: [13, 148, 136],
      marginTopPx: 2,
      marginBottomPx: 1,
    },
    "program.slot.room": {
      fontFamily: "helvetica",
      fontStyle: "normal",
      fontSize: 8.2,
      color: [120, 113, 108],
      marginTopPx: 2,
      marginBottomPx: 1,
    },
    "program.slot.title": {
      fontFamily: "helvetica",
      fontStyle: "bold",
      fontSize: 10,
      color: [41, 37, 36],
      marginBottomPx: 1.5,
    },
    "program.slot.meta": {
      fontFamily: "helvetica",
      fontStyle: "normal",
      fontSize: 8.8,
      lineHeight: 1.4,
      color: [87, 83, 78],
      marginBottomPx: 3,
    },
    "program.note": {
      fontFamily: "helvetica",
      fontStyle: "italic",
      fontSize: 8.4,
      lineHeight: 1.35,
      color: [120, 113, 108],
      marginTopPx: 5,
      marginBottomPx: 2,
    },
    "program.hidden.tags": {
      fontFamily: "helvetica",
      fontStyle: "normal",
      fontSize: 1,
      color: [255, 252, 248],
    },
  },
};
