module.exports = [
  {
    id: "newspaper-frontpage",
    title: "Newspaper Front Page",
    description: "Front-page editorial layout with masthead, pull quote, and footer band.",
    outputName: "newspaper-frontpage.pdf",
    themeFile: "theme-newsprint.js",
    sourceFile: "source-newspaper-frontpage.json",
    theme: require("./themes/theme-newsprint"),
    source: require("./sources/source-newspaper-frontpage.json"),
  },
  {
    id: "board-brief",
    title: "Board Brief",
    description: "Executive memo with metrics, decisions, risks, and operating notes.",
    outputName: "board-brief.pdf",
    themeFile: "theme-corporate.js",
    sourceFile: "source-board-brief.json",
    theme: require("./themes/theme-corporate"),
    source: require("./sources/source-board-brief.json"),
  },
  {
    id: "event-program",
    title: "Event Program",
    description: "Conference agenda with grouped sessions and page footer.",
    outputName: "event-program.pdf",
    themeFile: "theme-program.js",
    sourceFile: "source-event-program.json",
    theme: require("./themes/theme-program"),
    source: require("./sources/source-event-program.json"),
  },
  {
    id: "certificate",
    title: "Certificate",
    description: "Single-page ceremonial certificate with centered typography.",
    outputName: "certificate.pdf",
    themeFile: "theme-ceremony.js",
    sourceFile: "source-certificate.json",
    theme: require("./themes/theme-ceremony"),
    source: require("./sources/source-certificate.json"),
  },
  {
    id: "generic-document",
    title: "Generic Document",
    description: "Multi-section document with headings, body text, and bullet lists.",
    outputName: "generic-document.pdf",
    themeFile: "theme-default.js",
    sourceFile: "source-generic.json",
    theme: require("./themes/theme-default"),
    source: require("./sources/source-generic.json"),
  },
  {
    id: "article",
    title: "Article",
    description: "Long-form article with paragraphs and structured sections.",
    outputName: "article.pdf",
    themeFile: "theme-default.js",
    sourceFile: "source-article.json",
    theme: require("./themes/theme-default"),
    source: require("./sources/source-article.json"),
  },
  {
    id: "invoice",
    title: "Invoice",
    description: "Line-item invoice with metadata rows, totals, and payment notes.",
    outputName: "invoice.pdf",
    themeFile: "theme-default.js",
    sourceFile: "source-invoice.json",
    theme: require("./themes/theme-default"),
    source: require("./sources/source-invoice.json"),
  },
  {
    id: "magazine",
    title: "Magazine",
    description: "Editorial magazine layout with styled typography and pull quotes.",
    outputName: "magazine.pdf",
    themeFile: "theme-editorial.js",
    sourceFile: "source-magazine.json",
    theme: require("./themes/theme-editorial"),
    source: require("./sources/source-magazine.json"),
  },
  {
    id: "styled-invoice",
    title: "Styled Invoice",
    description: "Invoice with editorial theme styling, company branding, and detailed line items.",
    outputName: "styled-invoice.pdf",
    themeFile: "theme-editorial.js",
    sourceFile: "source-styled-invoice.json",
    theme: require("./themes/theme-editorial"),
    source: require("./sources/source-styled-invoice.json"),
  },
  {
    id: "financial-report",
    title: "Financial Report",
    description: "Financial report with tables, charts, and data-driven layouts.",
    outputName: "financial-report.pdf",
    themeFile: "theme-financial.js",
    sourceFile: "source-financial-report.json",
    theme: require("./themes/theme-financial"),
    source: require("./sources/source-financial-report.json"),
  },
  {
    id: "invoice-table",
    title: "Invoice with Table",
    description: "Invoice using native table operation for structured line items.",
    outputName: "invoice-table.pdf",
    themeFile: "theme-default.js",
    sourceFile: "source-invoice-table.json",
    theme: require("./themes/theme-default"),
    source: require("./sources/source-invoice-table.json"),
  },
];
