module.exports = [
  {
    id: "newspaper-frontpage",
    title: "Newspaper Front Page",
    description: "Front-page editorial layout with masthead, pull quote, and footer band.",
    outputName: "newspaper-frontpage.pdf",
    themeFile: "theme-newsprint.js",
    sourceFile: "source-newspaper-frontpage.json",
    theme: require("./themes/theme-newsprint"),
    source: require("./sources/source-newspaper-frontpage.json"),
  },
  {
    id: "board-brief",
    title: "Board Brief",
    description: "Executive memo with metrics, decisions, risks, and operating notes.",
    outputName: "board-brief.pdf",
    themeFile: "theme-corporate.js",
    sourceFile: "source-board-brief.json",
    theme: require("./themes/theme-corporate"),
    source: require("./sources/source-board-brief.json"),
  },
  {
    id: "event-program",
    title: "Event Program",
    description: "Conference agenda with grouped sessions and page footer.",
    outputName: "event-program.pdf",
    themeFile: "theme-program.js",
    sourceFile: "source-event-program.json",
    theme: require("./themes/theme-program"),
    source: require("./sources/source-event-program.json"),
  },
  {
    id: "certificate",
    title: "Certificate",
    description: "Single-page ceremonial certificate with centered typography.",
    outputName: "certificate.pdf",
    themeFile: "theme-ceremony.js",
    sourceFile: "source-certificate.json",
    theme: require("./themes/theme-ceremony"),
    source: require("./sources/source-certificate.json"),
  },
];
